### ISSUE TITLE
Loosen requirement on cue module

### ISSUE THREAD

**Issue by jilleJr** [stefanprodan/timoni#142]
Timoni requires a cue.mod folder per module.

I have a repo with multiple Helm charts. To start considering timoni for real, I would like to define multiple modules in a single repo.

With a single cue.mod at the repo root, I could make use of Cue's built in support to reference other files.

Imagine the folder structure:

- cue.mod/
- timoni-modules/
  - nginx/
  - podinfo/
- abstractions/
  - security-context.cue
  - ingress-with-certificate.cue

Then I could just reference my abstractions in any timoni module to reduce duplication.

This way, I would also only need to have Kubernetes cue files stored in one place.

Would this be feasible? Why does each module require its own cue.mod directory btw?

**Comment by stefanprodan** [comment]
I don't think loosening the CUE module requirement is possible as it would break core features. Having a monorepo for all the apps and all their templates under a single CUE module works until a certain scale.  If you want to move the abstractions to a diffrent repo, or have the apps managed in dedicated repos (per team for example), you'll need a way to manage dependencies between modules. On the bright side, there is a [proposal to add modules and package management to CUE](https://github.com/cue-lang/proposal/blob/main/designs/2330-modules-v2.md), which would make code reuse as easy as in Go 😄 

For now, to reuse cue code between modules, you can vendor the code under `cue.mod/` e.g. with `rsync`.

**Comment by jilleJr** [comment]
Hmm alright. Although if I understand that CUE package management proposal correctly, I would then still be forced to roundtrip via a registry just to have reusable code.

I find reusing code locally to be super important.

In Go, you cannot just reference a local module on a whim, but can freely reference stuff in the same module, but different packages. Same as in CUE.

However in Go, the result from a project could be multiple binaries, all from the same module. This is what I would like to replicate with Timoni.

That's what I meant with "loosening the requirement".

Maybe CUE's "ancestor packages" feature messes this up? (The part where it loads all files in parent directories with the same package name) Or maybe that could be used as an advantage?

**Comment by jilleJr** [comment]
Here's a thought: What if Timoni relied on CUE's upcoming package management completely? So instead of having your own packaging system, Timoni packages would just be CUE packages?

Personally, I would like if Timoni was only the "interpret CUE and do the logic to diff/apply changes to kubernetes". To fit that description, you could use CUE modules, CUE packages, or even a CUE file without a `package` statement at all.

Like, as long as the output matches the following schema:

```cue
#TimoniFile: {
	apiVersion: string | *"v1alpha1"
	metadata: {
		// Name of Timoni package
		name: string
		// Version of Timoni package
		version: string

		// Version of packaged app
		appVersion?: string
		// Authors of Timoni package
		maintainers?: [...string]
	}
	apply: {
		all: [...kubernetes.Object]
	}
}
```

Then what if Timoni accepted any CUE module, package, or file that resulted in above schema?

**Comment by stefanprodan** [comment]
It really depends on how upstream packages will work. If the CUE team opts to ship their own repository with no option to host and share packages independently, then we’ll definitely not do that in Timoni.

**Comment by stefanprodan** [comment]
Another reason for Timoni’s own module system is that it allows us to bundle containers images in the future. IMO a Timoni module should embed both config and app code e.g. the multi-arch layer of an app image. This way, you get a single artifact with deploy config, binaries, os, signatures, SBOMs, etc.

**Comment by jilleJr** [comment]
> Another reason for Timoni’s own module system is that it allows us to bundle containers images in the future. IMO a Timoni module should embed both config and app code e.g. the multi-arch layer of an app image. This way, you get a single artifact with deploy config, binaries, os, signatures, SBOMs, etc.

Oh that is an interesting use case!

Just to brainstorm though, could it be both? CUE package to just deploy Kubernetes resources, and then some own packaging format to do the extended stuff?

There's also other use cases that vanilla CUE doesn't support, that Helm users will be screaming for, such as:

- Doing if statements based on API versions found in Kubernetes
- Loading files, so you can have a separate `script.sh` file that you include in a ConfigMap, and then can run static code checking on the `script.sh` file

It's just that I think that Timoni should support a simple use case, and then can build on top of it. Instead of starting off complex. The fact that you need the `cue.mod` dir, `go.mod` and `go.sum` files, and then `timoni.cue` and `values.cue` seems extensive.

---

Anyway, I just wanted to express my concerns and seed that train of thought. If you think it's a bad fit for Timoni, then you're free to close this issue.

**Comment by stefanprodan** [comment]
The Timoni module would just be a layer in the multi-arch image same as Docker buildkit adds the SBOM layer. Scanners will skip unknown layers like SBOM today and look at the container layers only. This is solved by the OCI spec, TImoni's don't need to do nothing special.

**Comment by stefanprodan** [comment]
Going to close this issue, as loosening the requirement on cue module is not something that I would consider for Timoni.

**Comment by jilleJr** [comment]
Can an OCI image also contain multiple Docker images?

It's a very common use case to make use of a lot of different Docker images in the same Helm chart.

**Comment by stefanprodan** [comment]
How it could be done today is by using OCI Refs, Timoni would create an OCI artifact with the module in a layer, the bundles per env in different layers, will pull the app images from their origin repos and will push the images as separate artifacts to the same repo then add refs to the container images in the main artifact. This is what can be done today, but in future OCI could allow an index of indexes where all layers are bundles in a single artifact.

**Comment by jilleJr** [comment]
That's cool! Thanks for elaboration
