### ISSUE TITLE
Error creating a new module

### ISSUE THREAD

**Issue by mmorejon** [stefanprodan/timoni#143]
When I try to create a new module, I get an error.

```
$ timoni mod init github.com/mmorejon/microservices-docker-go-mongodb .
8:28PM ERR GET https://ghcr.io/token?scope=repository%3Astefanprodan%2Fmodules%2Fpodinfo%3Apull&service=ghcr.io: DENIED: denied
```

Any suggestion?

**Comment by stefanprodan** [comment]
Your GH token has expired, you need to delete it from the docker config or regenerate it. 

Also note that the init command should be called using the module name instead of full URL https://timoni.sh/cmd/timoni_mod_init/

**Comment by mmorejon** [comment]
Thanks, it works perfectly!

```
$ docker logout ghcr.io
Removing login credentials for ghcr.io
```

Then,

```
$ timoni mod init microservices-docker-go-mongodb .
5:21PM INF module initialized at microservices-docker-go-mongodb
```
