### ISSUE TITLE
Helm charts as dependencies and/or interoperability

### ISSUE THREAD

**Issue by verdverm** [stefanprodan/timoni#145]
There are a lot of good helm charts in the public, and many more in private

It would be nice to set these as a dependency in a bundle for deployment. (and maybe groups, but I haven't looked into those much yet).

This would enable us to weave existing helm into the timoni workflow

**Comment by stefanprodan** [comment]
You can place a Flux HelmRepository and [HelmRelease](https://fluxcd.io/flux/guides/helmreleases/) in a Timoni module then use it in bundles.

**Comment by verdverm** [comment]
Adopting flux is a big lift for this. Is there something more minimal for users that could be done?
