### ISSUE TITLE
Missing Kubernetes resources such as PersistentVolume and PersistentVolumeClaim

### ISSUE THREAD

**Issue by jpabbuehl** [stefanprodan/timoni#151]
hello,

First time Timoni user. exciting project !

After reading the tutorial, I would like to build a module running PostgreSQL with a persistent volume and persistent volume claim.

Unfortunately, I cannot see these resources defined in template folder, neither mentioned in template/config.cue

1. Is Timoni already supporting these resources?
2. Do I have to create myself these resource templates or can I auto-generate them via a magic command?

Thanks

**Comment by stefanprodan** [comment]
> Is Timoni already supporting these resources?

Yes, if you used `timoni mod init` then you have the Kubernetes core v1 definitions which include `#PersistentVolumeClaim`.

> Do I have to create myself these resource templates or can I auto-generate them via a magic command?

To get the Kubernetes API definitions, you would run:

```shell
go get k8s.io/api/core/v1@v0.27.3
cue get go k8s.io/api/core/v1
```

Then in the templates you can define a PVC such as:

```cue
package templates

import (
	corev1 "k8s.io/api/core/v1"
)

#MasterPVC: corev1.#PersistentVolumeClaim & {
	_config:    #Config
	apiVersion: "v1"
	kind:       "PersistentVolumeClaim"
	metadata:_ config.metadata
	spec: corev1.#PersistentVolumeClaimSpec & {
		storageClassName: _config.persistence.storageClass
		resources: requests: storage: _config.persistence.size
		accessModes: ["ReadWriteOnce"]
	}
}
```

Here is an example: https://github.com/stefanprodan/timoni/blob/5d5064d72364e46883cb62c9a1d02c92c5875bfc/examples/redis/templates/master.pvc.cue#L7
