### ISSUE TITLE
Generate CUE definitions from Kubernetes CRD YAMLs

### ISSUE THREAD

**Issue by stefanprodan** [stefanprodan/timoni#154]
Currently the way module authors can add Kubernetes definitions is by importing the Go package from a controller e.g. https://timoni.sh/module/#kubernetes-crds

```sh
# download the Prometheus Operator Go APIs
go get github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1@v0.63.0

# generate the CUE types for v1 monitoring APIs
cue get go github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1
```

But not all CRD controllers have public Go packages, for example Crossplane, as @vfarcic pointed out. There are also controllers written in other languages than Go. 

Timoni could offer a command for generating Kubernetes definitions from CRDs in YAML format. 

For example:

```sh
timoni mod import crd \
-f https://github.com/cert-manager/cert-manager/releases/download/v1.13.0/cert-manager.crds.yaml
```

This would generate the definitions inside `cue.mod/gen/` as such:

```
cue.mod/
└── gen
    ├── acme.cert-manager.io
    │   ├── challenge
    │   │   └── v1
    │   │       └── types_gen.cue
    │   └── order
    │       └── v1
    │           └── types_gen.cue
    └── cert-manager.io
        ├── certificate
        │   └── v1
        │       └── types_gen.cue
        ├── certificaterequest
        │   └── v1
        │       └── types_gen.cue
        ├── clusterissuer
        │   └── v1
        │       └── types_gen.cue
        └── issuer
            └── v1
                └── types_gen.cue
```

Not sure how can this be implemented, but I guess we could extract the OpenAPI v3 schema from the CRD YAML, and use cue to parse and generate the definitions.

**Comment by carlossg** [comment]
Not sure if this is what you are looking for, but this is a dirty way to get the schemas from the CRDs
https://github.com/adobe-platform/kubernetes-json-schema/blob/master/build.sh

**Comment by stefanprodan** [comment]
Maybe we could use [kube-openapi](https://github.com/kubernetes/kube-openapi) together with CUE's OpenAPI https://pkg.go.dev/cuelang.org/go/encoding/openapi

**Comment by sdboyer** [comment]
> Maybe we could use [kube-openapi](https://github.com/kubernetes/kube-openapi) together with CUE's OpenAPI 

IMO, https://pkg.go.dev/cuelang.org/go/encoding/openapi is absolutely the path to go for ingesting these types. We've used that package extensively in thema, and `thema lineage init openapi` (implementation starts [here](https://github.com/grafana/thema/blob/0e5575549ffb199b91fea58b13f8c1565d2c6733/cmd/thema/lineage_init.go#L290))

i'll take a swing at a PR to implement at least the part of this that massages an openapi document into timoni's expected form. i'm less clear on how kube-openapi could be used to to get that openapi document initially, but once i have those bytes, it should be straightforward.

**Comment by stefanprodan** [comment]
Thanks @sdboyer If we can get the yaml to cue part done it would be a great first step. It doesn’t need to fetch the crd yaml from the API or from some remote URL, just from a local file would suffice.
