### ISSUE TITLE
support for CUE tags

### ISSUE THREAD

**Issue by verdverm** [stefanprodan/timoni#157]
i.e. the `-t` flag and `@tag()`

which can be filled into the load.Config: https://github.com/stefanprodan/timoni/blob/3e99a6045487156a2e235d525aa446f2b5b09789/internal/engine/module_builder.go#L127

**Comment by stefanprodan** [comment]
CUE tags are not supported, you can use Timoni’s own env tags which support multi-line strings, please see https://timoni.sh/bundles/#values-from-environment-variables

**Comment by verdverm** [comment]
I know that ENV VARS are supported, but being able to set single values with a flag is a preferable ux

**Comment by stefanprodan** [comment]
Ah forgot to mention that you can set values at runtime using a pipe:

```
echo 'bundle: instances: app: values: somekey: someval' | timoni bundle apply -f bundle.cue -f-
```

**Comment by verdverm** [comment]
The main problem with ENV VARs is when a user has an value already set and does not update date it. There is the potential for accidentally picking up values automatically vs always having to be explicit about what you are passing. This is one of CUE's methods for preserving hermeticity between user environments.

The main reason for requesting is UX. Almost ever tool accepts flags for providing runtime values, CUE included via the `-t` flag. It would be better, imo, to expose CUE's `@tag` directly, which also supports ENV VARs, and then find another temp solution for files until CUE supports that natively as well.

I would love to see Timoni hold CUE more naturally. Right now it is a little too different / weird for someone coming from CUE. Passing the CUE files as entrypoints rather than with the -f flag would be good too.

**Comment by stefanprodan** [comment]
> I would love to see Timoni hold CUE more naturally. Right now it is a little too different / weird for someone coming from CUE. Passing the CUE files as entrypoints rather than with the -f flag would be good too.

Timoni is targeted at Kubernetes and Docker users, the CLI is build on top of `k8s.io/cli-runtime` and it follows the CLI conventions used by CNCF projects e.g. `kubectl apply -f-`, `docker build -f`, `helm install -f`, etc. 

I'm for finding a middle group between CUE and the CNCF landscape, but TImoni to succeed it needs to feel natural to Kubernetes/Helm/etc users.

**Comment by hiddeco** [comment]
From a Helm perspective, one could argue that `-t` acts like Helm's `--set`.

**Comment by stefanprodan** [comment]
Yeah one option would be to allow users to set values for `@timoni(env:string:key)` with `timoni bundle --set key=value`, the values supplied as cmd args would override the ENV.

**Comment by hiddeco** [comment]
What about a `@timoni(tag:key, env:string:key`) kind of approach? It feels weird to me to build an entire thing around environment variables, which seems a brittle foundation.

**Comment by stefanprodan** [comment]
Yeah that's also a good option IMO, but it will be `@timoni(tag:<type>:key)`.

**Comment by verdverm** [comment]
why create a new `@timoni` attribute which does basically the same thing as CUE's `@tag`?

By creating a new attribute, you force users to double "tag" their fields, if they want to use the standard CUE tooling for debugging etc...

**Comment by stefanprodan** [comment]
As a module author you can use CUE tags and tools to debug, see here an example:
- debug tags https://github.com/stefanprodan/timoni/blob/main/examples/podinfo/test_values.cue
- debug tools https://github.com/stefanprodan/timoni/blob/main/examples/podinfo/test_tool.cue


The Bundle API is for end-users, those that consume ready-made modules published with Timoni to registries. A bundle can’t be debugged with the CUE CLI, as this is a Timoni specific API that involves OCI and Kubernetes operations.

**Comment by verdverm** [comment]
So you are saying I should not expect to be able to `cue eval timoni.cue`  or eval my template files? 

Or that I cannot import a my own CUE into timoni.cue or the templates?

**Comment by stefanprodan** [comment]
No I’m saying the opposite, as a module author you can use CUE tooling on Timoni modules, and do whatever you you want in the module dirs, templates, etc. Modules and Bundles are different things.

**Comment by stefanprodan** [comment]
@verdverm Timoni v0.14 ships now with a module template that allows debugging with CUE tags. 

When creating a module with `timoni mod init my-app .` you'll see two files `debug_values.cue` and `debug_tool.cue`.
These files contain the instructions of how to run `cue` to mimic what `timoni build` does. 

In the `debug_values.cue` you can set CUE tags, then you can test various settings using `cue eval` or the provided tools.

For example, edit `debug_values.cue` and add a CUE tag to set the container image repo:

```cue
@if(debug)

package main

values: {
	podAnnotations: "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
	message: "Hello Debug"
	image: {
		repository: string @tag(image,type=string)
		tag:        "1-alpine"
		digest:     ""
	}
}
```

Now you can inject the image value and evaluate the generated objects with the cue CLI:

```shell
cue -t debug \ # use the debug values
 -t name=test -t namespace=test -t mv=1.0.0 -t kv=1.28.0 \ # inject Timoni's required tags
 -t image='docker.io/nginx' \ # inject custom tags
 eval -e timoni.instance.objects.deploy.spec.template.spec.containers[0].image
```

I'm going to close this issue as completed as there is now a way to use CUE tags for debugging modules. 

Using CUE tags in Timoni's bundles is not something that I'm considering doing. The Timoni Bundle API has been extended with the Timoni Runtime API, which allows end-users to inject values from Kubernetes clusters or from the local environment. You can read all about the Bundle Runtime API here: https://timoni.sh/bundle-runtime/
