### ISSUE TITLE
Update Readme file with values available in the module

### ISSUE THREAD

**Issue by mmorejon** [stefanprodan/timoni#168]
How to generate a markdown table inside the README file with the variables available in the module?

**Comment by mmorejon** [comment]
Generating good documentation in a README markdown format is a good starting point for users to understand the options available inside Timoni modules. It is not easy to discover all options through multiple `.cue` files.

At this moment Helm doesn't have this option in its commands either. Is it possible to extract and generate all available options from Timoni's module?

**Comment by stefanprodan** [comment]
The options could be extracted from the `#Config` which is defined in `templates/config.cue`. We could come up with a convention for comments and extract them to Markdown table, something like:

```cue
#Config: {
	// Runtime version info
	moduleVersion!: string
	kubeVersion!:   string

	// DOC
	// Set custom annotations and labels to all resources.
	// Note that the `app.kubernetes.io/name` and `app.kubernetes.io/version` labels
	// are automatically injected and can't be overwritten.
	metadata: timoniv1.#Metadata & {#Version: moduleVersion}

	// DOC
	// Set the number of replicas, defaults to `1`.
	replicas: *1 | int & >0
	
	// DOC
	// Set custom annotations to pods.
	podAnnotations?: {[ string]: string}
	
	// DOC
	// Set [Kubernetes pod security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context) (optional).
	podSecurityContext?: corev1.#PodSecurityContext
}
```

We can use the CUE AST to walk the file line by line, once we encounter a comment that starts with `DOC`, we would take the name and type of that field and write it to stdout as a makrdown row. 

There are many challenges with this, complex types have their own schema which can contain tens of fields, people may want to add comments to sub-fields of a complex type. It's hard to determine the defaults for complex type as those could come from the upstream schema, e.g. `ClusterIP` for `Service.Type`.

**Comment by mmorejon** [comment]
You are right. It is not easy to cover all possible cases for complex types. Anyway, the use of `DOC` convention could be a good starting point for primitive types.
