### ISSUE TITLE
Namespace config are not applied

### ISSUE THREAD

**Issue by b4nst** [stefanprodan/timoni#202]
It seems namespaces are processed as separated resources. I tried something like:
```cue
// templates/namespace.cue
package templates

import (
	corev1 "k8s.io/api/core/v1"
)

#Namespace: corev1.#Namespace & {
	_config:    #Config
	apiVersion: ""
	kind:       "Namespace"

	metadata: {
		name:   _config.metadata.namespace
		labels: _config.metadata.labels & {
			"custom.label/tier": "development"
		}
		if _config.metadata.annotations != _|_ {
			annotations: _config.metadata.annotations
		}
		annotations: "cnrm.cloud.google.com/project-id": "\(_config.provider.projectID)"
	}
}
```

with

```cue
// tempaltes/config.cue
package templates

import (
	timoniv1 "timoni.sh/core/v1alpha1"
	konf "cue.company.com/kue/pkg/config"
)

// Config defines the schema and defaults for the Instance values.
#Config: {
	// Runtime version info
	moduleVersion: string
	kubeVersion:   string

	// Metadata (common to all resources)
	metadata: timoniv1.#Metadata
	metadata: version: moduleVersion

	// Provider info
	provider: konf.#GCP // comes from our lib but basically contains projectID

	//...other settings
}

// Instance takes the config values and outputs the Kubernetes objects.
#Instance: {
	config: #Config

	objects: {
		ns:          #Namespace & {_config:   config}
		// ...other resources
	}
}
```

All resources are correctly applied, however the namespace is not deployed (nor updated if it exists) with the custom labels and annotations.
Is there a way to change this behavior? Or maybe I missed something in the doco?

**Comment by stefanprodan** [comment]
You're missing the `apiVersion` so the server-side applier drops it from the resource set, see https://github.com/stefanprodan/flux-aio/blob/7f02017c923c25cf1b7bf81430a84a59464e14f8/modules/flux-aio/templates/namespace.cue#L9

Too bad that CUE generates this very loose schema of Kubernetes APIs, the `apiVersion` should be a required field with a min len of 1.

**Comment by stefanprodan** [comment]
@b4nst the next version of Timoni will come with vendoring commands for the Kubernetes APIs and CRDs. For the CRDs, we are setting the `apiVersion` and `kind` in the schemas, so you can't specify them in the templates as they are set by Timoni. For the Kubernetes core APIs, I've setup up https://github.com/stefanprodan/kubernetes-cue-schema we need to figure out how to set the `apiVersion` and `kind` in the schemas so people can't make these mistakes anymore.

**Comment by b4nst** [comment]
Pfahaha I feel so dumb! Thanks for catching that, for some reason it got out of my sight 😆. Works as expected.
> Too bad that CUE generates this very loose schema of Kubernetes APIs
Yeah I 💯 agree. We used to have a custom lib on top of it, but it was cumbersome to maintain.

We could also go for a simple 

```cue
// cue.mod/usr/k8s.io/api/core/v1/namespace.cue
package v1

#Namespace: {
	apiVersion: "v1"
	kind:       "Namespace"
}
```

but I yet have to find a good way of either pulling that from somewhere, or even better generating it. The nice thing about the `usr` folder is that you keep using the same package import.

**Comment by stefanprodan** [comment]
@b4nst the Kubernetes Swagger file has the preferred apiVersion for each kind, I would fetch that for each minor version then inject in these files https://github.com/stefanprodan/kubernetes-cue-schema/blob/main/schemas/v1.28/k8s.io/api/apps/v1/types_go_gen.cue
