### ISSUE TITLE
Use CUE default values instead of values.cue

### ISSUE THREAD

**Issue by fionera** [stefanprodan/timoni#252]
Hi,

new to timoni and I just read the documentation. Why is timoni using/recommending a -values.cue file instead of using CUE default values? Instead of 
```cue
values: {
    resources: requests: {
        cpu:    "100m"
        memory: "128Mi"
    }
    resources: limits: resources.requests
}
```

you could use this:
```cue
resources: { 
  requests: {
    cpu:    string | *"100m"
    memory: string | *"128Mi"
  }
  limits: requests
}
```

**Comment by stefanprodan** [comment]
To allow various constructs in CUE file, besides `values` you could have some other fields, schemas, etc that Timoni will ignore. As with `values:`, there is also `bundle:` and `runtime:`, all follow the same convention.

**Comment by fionera** [comment]
yes but you could skip the whole `values:` struct which is how I see it borrowed from the Helm design, as you can always set default values for fields inside CUE

**Comment by stefanprodan** [comment]
The `values` field from the user supplied CUE file is used for unification with the `values` schema from inside the module. But regardless of the values file structure, how Timoni would be used is via Bunde files, where `values` is a property of the instance e.g.

```cue
bundle: {
    apiVersion: "v1alpha1"
    name:       "podinfo"
    instances: {
        redis: {
            module: {
                url:     "oci://ghcr.io/stefanprodan/modules/redis"
                version: "7.2.2"
            }
            namespace: "podinfo"
            values: maxmemory: 256
        }
        podinfo: {
            module: url:     "oci://ghcr.io/stefanprodan/modules/podinfo"
            module: version: "6.5.3"
            namespace: "podinfo"
            values: caching: {
                enabled:  true
                redisURL: "tcp://redis:6379"
            }
        }
    }
}
```

**Comment by fionera** [comment]
What I mean is that everything the `values` struct does is provide values for the instance to use. Everything inside the `values` struct inside the bundle (values that are optional to be set by the user and set to a default) could be removed and replaced by CUE default values. Since CUE allows to override them you don't have to expose everything as value. 

I will add another code example with the difference later but currently on the run :D

**Comment by fionera** [comment]
I sadly dont have time right now to build an example. But what I meant was to replace the whole values structure as its just smth that helm needed. In CUE you could always allow all values to be overrideable and provide a default, which is what I meant. I will reopen this issue as soon as I got time
