### ISSUE TITLE
`timoni mod vet` Name

### ISSUE THREAD

**Issue by Nalum** [stefanprodan/timoni#269]
Should `timoni mod vet` also accept a `name` for use in `@tag(name)`, there is a `--namespace` flag but nothing to allow setting `name`.

**Comment by stefanprodan** [comment]
We could add `--name` that defaults to `default` and map both the name and namespace arg to the underlying build command. Would you want to contribute this feature?

**Comment by Nalum** [comment]
Yeah, I can look at doing this :+1:
