### ISSUE TITLE
[Proposal] Replace --debug with --file for vet

### ISSUE THREAD

**Issue by b4nst** [stefanprodan/timoni#288]
Currently the `vet` command only accepts a `--debug` boolean argument to be able to vet the module against `debug_values.cue` file.
I find this file quite confusing, and often removes it all together with the `debug_tool.cue`. I think it would be useful for the `vet` command to take a `--values` (or `--value` if we want to keep it simple) argument, and vet against those(this) values file(s).

It would help us testing complex module where there's mutually exclusive configuration value (cloud provider for example).

What do you think @stefanprodan? If ok with you I can push a PR

**Comment by stefanprodan** [comment]
I'm Ok adding `-f, --values strings` same as the for the `timoni build` command. I'm using `--debug` in lots of places, so please leave that as it is, if custom values are provided, those would take precedence over debug.

**Comment by b4nst** [comment]
Copy, thanks! Will push you a MR today
