### ISSUE TITLE
Simple install without brew

### ISSUE THREAD

**Issue by zs-dima** [stefanprodan/timoni#295]
Brew does not support ARM64.
Could be nice to have simple way to install timoni without installling Brew or Go.

https://timoni.sh/install/

**Comment by stefanprodan** [comment]
> Brew does not support ARM64.

The Brew formula for Timoni supports ARM64 for both macOS and Linux, see https://github.com/stefanprodan/homebrew-tap/blob/main/Formula/timoni.rb

> Could be nice to have simple way to install timoni without installing Brew or Go.

There is simple way, you can download the binary from the [release page](https://github.com/stefanprodan/timoni/releases) and run it. Timoni has no OS dependencies and works on any Windows, Linux and macOS machine.

**Comment by zs-dima** [comment]
@stefanprodan thanks a lot for the answer
> The Brew formula
ARM (unsupported) - https://docs.brew.sh/Homebrew-on-Linux
I mean brew itself does not support ARM64 officially

> download the binary
Thanks a lot, could be nice to add it to install doc

**Comment by stefanprodan** [comment]
The first paragraph on the install page say:
> Timoni is available as a binary executable for Linux, macOS and Windows. The AMD64 and ARM64 binaries can be downloaded from GitHub [releases](https://github.com/stefanprodan/timoni/releases).
