### ISSUE TITLE
ERR loading kubeconfig failed: stat ~/.kube/config:: no such file or directory

### ISSUE THREAD

**Issue by JCzz** [stefanprodan/timoni#300]
os: macos arm64 m1

installed with brew
timoni -v
timoni version 0.18.0

timoni -n test apply podinfo oci://ghcr.io/stefanprodan/modules/podinfo --version latest
2:30PM INF i:podinfo > pulling oci://ghcr.io/stefanprodan/modules/podinfo:latest
2:30PM INF i:podinfo > using module timoni.sh/podinfo version 6.5.4
2:30PM ERR loading kubeconfig failed: stat /Users/christian/.kube/config:: no such file or directory

The file is there: "~/.kube/config"

**Comment by stefanprodan** [comment]
Do you have the `KUBECONFIG` environment variable set by any chance? Can you please try:
```
timoni -n test apply podinfo oci://ghcr.io/stefanprodan/modules/podinfo \
--kubeconfig ~/.kube/config
```

**Comment by JCzz** [comment]
Thanks, yes that worked. Strange now that kubectl is working on the same cluster.

Nive work and looking forward to follow you work.

**Comment by stefanprodan** [comment]
It may be related to #309 Do you have multiple config files in the `KUBECONFIG` env var?
