### ISSUE TITLE
Document how inventory is managed

### ISSUE THREAD

**Issue by jmgilman** [stefanprodan/timoni#306]
When creating a new instance using `timoni apply` the documentation mentions the following:

```
Creates or updates the instance inventory with the last applied resources IDs.
```

I cannot find any additional information on how this is being managed. Where is the instance inventory stored in the cluster? In one recent case, I managed to create a resource that Timoni was unable to delete without an error. This caused the instance to never truly delete and it wasn't apparent to me where Timoni was looking to find this inventory information so I could manually purge it.

**Comment by stefanprodan** [comment]
> I managed to create a resource that Timoni was unable to delete without an error. 

Was this an RBAC issue, did the account used by Timoni didn't had rights to delete but only create/update?

**Comment by jmgilman** [comment]
> > I managed to create a resource that Timoni was unable to delete without an error.
> 
> Was this an RBAC issue, the account used by Timoni didn't had rights to delete but only to create/update?

No, I managed to create an object with no namespace (which IIRC k8s defaults to the `default` namespace). When Timoni went to delete it, it was throwing an error about a namespace being required to delete the object.

**Comment by stefanprodan** [comment]
Hmm but Timoni should error out for namspaced objects without a namespace specified. Can you say more how you got into this situation?

**Comment by stefanprodan** [comment]
In #301 I've added a section to the module spec to document the instance storage. Please let me know if it solves this issue.
