### ISSUE TITLE
Provide a way to update timoni package

### ISSUE THREAD

**Issue by jmgilman** [stefanprodan/timoni#313]
At the moment, Timoni uses the `timoni.sh/core/v1alpha1` definitions from the template that is pulled when `timoni mod init` is run. The problem is that this doesn't allow easy upgrading of the definitions when changes are made in this repository. 

This is more of a tracking issue because I suspect it's not worth solving until the CUE modules work is done. They are [currently holding feedback sessions](https://github.com/cue-lang/cue/discussions/categories/announcements?discussions_q=is%3Aopen+category%3AAnnouncements+label%3Amodules) for the related development. At a certain point, when we feel things are stable enough, we should switch to using the new implementation so that (hopefully) upgrades are possible in the future.

**Comment by stefanprodan** [comment]
Here are the docs for keep them up to date: https://github.com/stefanprodan/timoni/tree/main/schemas#vendoring

I need to add these to the docs website.

**Comment by jmgilman** [comment]
I wasn't even aware of the `timoni artifact` subcommand :) I guess this changes the question: do you forsee there being value in switching over to using [modules](https://github.com/cue-lang/cue/discussions/2330) for managing this once development is complete?

**Comment by stefanprodan** [comment]
The `timoni artifact` commands are more for sharing bundle files, which may not necessary be CUE.

When CUE adds support for modules, then we'll publish the Timoni's schemas as a module so it can be updated with `cue`.  Right now you can abuse 😄 the `timoni artifact` commands to manage `cue.mod`, I see no reason to do that when `cue` will have this capability.
