### ISSUE TITLE
Add support for cluster validation

### ISSUE THREAD

**Issue by jmgilman** [stefanprodan/timoni#317]
One nice feature of [tanka](https://tanka.dev) is the built-in support for tying an environment to a specific Kubernetes endpoint. This prevents a potentially catastrophic situation where you deploy to the wrong environment.

For Timoni, I think we can replicate this in the bundle schema. Add an _optional_ field for specifying which cluster a particular bundle belongs to. How Timoni uses this can be one of two ways:

1. When doing an `apply` operation, it compares the configured cluster endpoint to the one it connects to and refuses to deploy if they are different.
2. When doing an `apply` operation, attempt to automatically use the correct Kubernetes credentials using the configured cluster endpoint (this is how Tanka operates by default).

**Comment by stefanprodan** [comment]
Have you looked into Timoni’s Runtime?

**Comment by jmgilman** [comment]
I haven't, but that looks to pretty much solve the problem. Thanks for the tip! :)
