### ISSUE TITLE
PodSecurity Violation

### ISSUE THREAD

**Issue by Nalum** [stefanprodan/timoni#322]
Working on a module for [trust-manager](https://github.com/cert-manager/trust-manager/) I've hit a possible nice to have, I installed my [cert-manager module](https://github.com/nalum/cert-manager-module) which sets up a restricted PodSecurity on the cert-manager namespace, I then install trust-manager but get a warning from timoni about violating the PodSecurity:

```
9:33AM INF would violate PodSecurity "restricted:latest": host namespaces (hostNetwork=true), hostPort (container "trust-manager" uses hostPorts 6443, 9402) logger=KubeAPIWarningLogger
```

Timoni continues on with the apply, would it be better to kill the apply at this point rather then have it eventually timeout?

**Comment by stefanprodan** [comment]
Timoni can't break the execution on warning messages, PodSecurity does not fail the apply like a validation webhook would do, it just issues a message. Warning messages are issued by the API for all sorts of situations, for example deprecated fields, so stopping the apply would be a mistake,

**Comment by Nalum** [comment]
Ah so it'd need to parse the message and that is definitely not something we'd want to do. Grand.

**Comment by stefanprodan** [comment]
We can't parse the warning, these get logged by the underling client-go logger, these are not errors retuned by the SSA operations.
