### ISSUE TITLE
[Proposal] Module should support profiles

### ISSUE THREAD

**Issue by yyvess** [stefanprodan/timoni#332]
Actually a Timon module can have only one default value file.

User experience will be simplified (comparing to helm including) if a module can declare a list of supported profile as

- high-availability 
- ingress | istio |  gateway.k8s
- network-policy
- statefull  <- enforce that data is not store on empty dir as exemple

Bundle file should allow to actives one or more profiles.

```
bundle: {
    apiVersion: "v1alpha1"
    name:       "podinfo"
    instances: {
        redis: {
            module: {
                url:     "oci://ghcr.io/stefanprodan/modules/redis"
                version: "7.2.3"
            }
            namespace: "podinfo"
            profiles: ['high-availability', 'ingress' ]
            values: maxmemory: 256
        }
    }
}
```

Activation of a profile will load transparently additional values file that is included on the module similar to 
```
 --values ../values.cue --values ./values-high-availability.cue --values ./values-ingress.cue
```

Supported profiles can be declared on the module file timoni.cue or simply by listing all root file named values-*.cue

An value-high-availability.cue can look as =>

```
values: {
	replicas: *2 | int & >2
	pdbCreate: true
}
```

**Comment by jmgilman** [comment]
The use case sounds great, but the proposed implementation seems extremely opinionated. In other words, it seems like the root problem is conditionally adding additional input files when a bundle is built. If this functionality was supported, you could build out a "profile" system without necessarily implementing on top of Timoni.

**Comment by stefanprodan** [comment]
This can be achieved by making your modules expose the opinionated profiles in their values. Example here: https://github.com/stefanprodan/flux-aio/blob/b8282e46dc7456dce5d4d0ea12a6527ed0f68ef2/modules/flux-aio/templates/config.cue#L65
