### ISSUE TITLE
Local module reference fails when applying multi-clusters

### ISSUE THREAD

**Issue by b4nst** [stefanprodan/timoni#364]
When applying a bundle containing a local module reference with a multi cluster runtime, only the first cluster passes. The second one always fails with this kind of error:

```trace
11:55AM ERR module not found at path /var/folders/vl/j712bqm55gd754rr5tdm8bxm0000gn/T/timoni3063563812/gcp-eu/examples/redis
```

A simple test can be run in this repository by creating this bundle and runtime at the root of the repo:

```cue
// bundle.cue
bundle: {
	apiVersion: "v1alpha1"
	name:       "debug"
	instances: {
		redis: {
			module: url: "file://./examples/redis/"
			namespace: "default"
			values: maxmemory: 256
		}
	}
}
```

```cue
// runtime.cue
runtime: {
	apiVersion: "v1alpha1"
	name:       "production"
	clusters: {
		"first": {
			kubeContext: "local"
			group:       "test1"
		}
		"second": {
			kubeContext: "local"
			group:       "test2"
		}
	}
}
```

```shell
timoni bundle apply -f bundle.cue --runtime runtime.cue --diff
```

**Comment by huguesalary** [comment]
Looked into this and created Draft PR https://github.com/stefanprodan/timoni/pull/429

I'm not super familiar with Timoni's codebase, so while this fix works, I don't know if it _actually_ makes sense.
