### ISSUE TITLE
Custom resource names

### ISSUE THREAD

**Issue by salotz** [stefanprodan/timoni#369]
I am trying to write a module where one of the K8s resources (a Secret) is expected by other modules in my bundle to be of a specific name (i.e. `gar-secret`).

I'm trying to figure out the proper place to configure this.

Currently I have this workaround:

```cue
package templates

import (
	corev1 "k8s.io/api/core/v1"
	"encoding/base64"
)

#PullSecret: corev1.#Secret & {
	#config: #Config
	apiVersion: "v1"
	kind:       "Secret"
	metadata: name: #config.secretName
	// metadata: name: #config.secretName
	metadata: {
		namespace: #config.metadata.namespace
		labels: #config.metadata.labels
	}
	
	if #config.service.annotations != _|_ {
		metadata: annotations: #config.service.annotations
	}
	type: corev1.#SecretTypeDockerConfigJson
	// NOTE: that base64.Encode returns a string, so we interpolate to bytes
	data: ".dockerconfigjson": '\(base64.Encode(null, #config.dockerConfigJson))'
}
```

Following the example suggested here: https://github.com/stefanprodan/timoni/issues/85#issuecomment-1840700292

Which is undesirable since I have to dig into the `#Metadata` to understand the rest of the fields I have to fill in.

---
This might be a cue question, but it might impact the way the `#Metadata` definition is written as well.

For instance in Python if I wanted to combine a struct/dict except one field I could do something like this:

```python
{
    "name" : "static-forced-name",
    *{k : v for k, v in config.metadata.items() if k != 'name'},
}
```

Is there a similar operator in cue?

---

On the Timoni side in `timoniv1.core.v1alpha1` I worry that the `StdLabel*` labels would be set wrong.

Concretely you have this:

```cue
	labels: {
		(#StdLabelName):      name
		(#StdLabelVersion):   #Version
		(#StdLabelManagedBy): "timoni"
	}

	// LabelSelector selects Pods based on the app.kubernetes.io/name label.
	#LabelSelector: #Labels & {
		(#StdLabelName): name
	}
```

But I wonder if `#StdLabelName` (aka `app.kubernetes.io/name` shouldn't actually be `#InstanceName`, etc.

And might there be a way to change the `#Metadata` definition to allow setting of resource names. In general I find that workaround for adding suffixes to the name unsatisfactory for all of the same reasons.

Currently this make setting up multiple different resources in the same timoni Instance fairly difficult and fragile. You can choose to not use `#Metadata` but I would imagine that might impact the ability of Timoni to actually manage resources if it depends on certain labels or resource names.

Any feedback whether my workaround is sound or if this is something that just requires some changes to Timoni?

**Comment by salotz** [comment]
Really surfing the latest in the Cue world. They just started serving the new docs which provides some more guidance on field comprehensions, e.g. something like this should work. I'll give it a try.

```cue
metadata: {name: #config.secretName} & {
    for key, value in #config.metadata
    if key != "name"
    let key = value
}
```

**Comment by stefanprodan** [comment]
There is a generator for image pull secrets that accepts a suffix, see https://github.com/stefanprodan/timoni/blob/main/schemas/timoni.sh/core/v1alpha1/imagepullsecret.cue

>  I would imagine that might impact the ability of Timoni to actually manage resources if it depends on certain labels or resource names.

No, Timoni does not depend on any use-defined labels nor resource naming conventions to function correctly. You can roll your own Metadata.

**Comment by salotz** [comment]
> No, Timoni does not depend on any use-defined labels nor resource naming conventions to function correctly. You can roll your own Metadata.

Good to know! I actually did end up do this and roll it up into my own Cue module. I'll look to share after I develop it some more at least as an example.

> There is a generator for image pull secrets that accepts a suffix

I saw this but it wouldn't work in this case since the dependency is on a specific name, not just a prefix.
