### ISSUE TITLE
timoni `--namespace` doesn't respect the default ns set in kubeconfig context

### ISSUE THREAD

**Issue by r0bnet** [stefanprodan/timoni#39]
Hey,

I have an issue with the `timoni list` command. It should show me all the installed instances in the current namespace but the list is empty except when I explicitly use the `-A` or `-n test` flag.

**Steps to reproduce**
```bash
kubectl create namespace test
kubectl config set-context --current --namespace=test
timoni -n test apply podinfo oci://ghcr.io/stefanprodan/modules/podinfo --version latest
timoni list
```

**Expected output**
```bash
NAME   	MODULE                                    	VERSION	LAST APPLIED         
podinfo	oci://ghcr.io/stefanprodan/modules/podinfo	6.3.4  	2023-03-31T13:37:18Z
```

**Actual output**
```bash
NAME	MODULE	VERSION	LAST APPLIED
```

**Additional info**
Using the `-n test` flag explicitly or the `-A` flag works but I thought it should also work without it when I'm on the right namespace already. Is that the intended behavior or a bug?

**Comment by stefanprodan** [comment]
This is the intended behaviour, as the `--namespace` flag is decoupled from the context. But I realise it may not be the best thing, following the kubectl behaviour would be better. This is not specific to `list` all commands behave the same, can you confirm that this please?

**Comment by r0bnet** [comment]
I tested with delete and it's the same behavior. It's nothing overly dramatic but I'm used to switch the namespace quite often with `kubens` so I noticed this thing quite early ;)

**Comment by r0bnet** [comment]
I tested with `delete` and it's the same behavior. It's nothing overly dramatic but I'm used to switch the namespace quite often with `kubens` so I noticed this thing quite early ;)
