### ISSUE TITLE
Expose Go Bundle structure

### ISSUE THREAD

**Issue by jmgilman** [stefanprodan/timoni#426]
We have a need for generating Timoni Bundle files internally. Unfortunately, the Go structure is [hidden](https://github.com/stefanprodan/timoni/blob/cf22fe34b1419038785b302090bb566aefb848c5/internal/engine/bundle_builder.go#L49) behind the internal package, even though the CUE schema [is not](https://github.com/stefanprodan/timoni/blob/main/api/v1alpha1/bundle.go). Unfortunately, generating Go from CUE is much more complex than going the other way.

Can we perhaps expose this (or a better) struct publicly?

**Comment by stefanprodan** [comment]
The reason for this is that the deepcopy generator trips over `cue.Value`. We could probably exclude this with a controller gen comment.
