### ISSUE TITLE
Helm OCI image is not supported in flux-aio

### ISSUE THREAD

**Issue by datapedd** [stefanprodan/timoni#447]
I have flux-aio installed (inside talos).
[flux-aio.txt](https://github.com/user-attachments/files/17894121/flux-aio.txt)

Then I have installed the postgresql version which has until now worked, but now it is not anymore:
[postgres.txt](https://github.com/user-attachments/files/17894124/postgres.txt)

I thought that flux-aio has oci automatically enabled, but I am not so sure:
As the new postgres version is a oci image and not a tgz anymore. I get the error in flux-system:
{"level":"error","ts":"2024-11-24T17:01:41.761Z","msg":"Reconciler error","controller":"helmchart","controllerGroup":"source.toolkit.fluxcd.io","controllerKind":"HelmChart","HelmChart":{"name":"coder-coder-db","namespace":"coder"},"namespace":"coder","name":"coder-coder-db","reconcileID":"502ecb54-0e7e-4a30-8570-a7df6c6cb2f0","error":"chart pull error: failed to download chart for remote reference: Get \"oci://registry-1.docker.io/bitnamicharts/postgresql:16.2.2\": unsupported protocol scheme \"oci\""}

**Comment by stefanprodan** [comment]
You need to set the Bitnami repository OCI URL like this:

```cue
bundle: {
    apiVersion: "v1alpha1"
    name:       "coder-deployment"
    instances: {
        // PostgreSQL Deployment using Bitnami Helm Chart
        "coder-db": {
            module: {
                url:     "oci://ghcr.io/stefanprodan/modules/flux-helm-release"
                version: "latest"
            }
            namespace: "coder"
            values: {
                repository: {
                    // Use Bitnami's DockerHub repository
                    url: "oci://registry-1.docker.io/bitnamicharts"
                }
                chart: {
                    name:    "postgresql"
                    version: "*"
                }
                helmValues: {
                    fullQualifiedName: "coder-db-postgresql"
                    auth: {
                        username: "coder"
                        password: "coder"
                        database: "coder"
                    }
                    persistence: {
                        size: "10Gi"
                    }
                }
            }
        }
	}
}
```
