### ISSUE TITLE
Update CUE API

### ISSUE THREAD

**Issue by jmgilman** [stefanprodan/timoni#457]
The current version of the [CUE Go API](https://github.com/stefanprodan/timoni/blob/53b4f415520546a95925b68c37511a13e36872ed/go.mod#L6) appears to be quite outdated. This is also confirmed via the CLI:

```
❯ timoni version
api: timoni.sh/v1alpha1
client: 0.22.1
cue: 0.9.2
```

I am attempting to use symlinks in my `cue.mod/pkg` directory, but support for this was added after `0.9.2`. I recommend bumping to the latest stable version: `0.11.0`.

**Comment by jmgilman** [comment]
Hey @stefanprodan, thanks for merging! Do you know when you plan to cut another release?

**Comment by stefanprodan** [comment]
New release here https://github.com/stefanprodan/timoni/releases/tag/v0.23.0
