### ISSUE TITLE
Write a comparison to Helm 

### ISSUE THREAD

**Issue by stefanprodan** [stefanprodan/timoni#50]
Feedback from people posting on social media is that Timoni's docs lack a detailed comparison of features to Helm. The doc should highlight the major differences like modules vs charts, values files CUE vs YAML, instances vs releases, server-side apply vs Helm 3-way-merge, CRDs upgrades vs Helm broken CRD support, bundles.

**Comment by AMK9978** [comment]
Hey Stefan. I just saw timoni and I'm totally naive to it, but it seems interesting to me, and I want to contribute to it, though, I'm not aware of the roadmap of the development, and its future features other than the open issues. Would you open some issues?
