### ISSUE TITLE
Reference modules by OCI digest in bundles

### ISSUE THREAD

**Issue by stefanprodan** [stefanprodan/timoni#59]
While a Timoni Module version should be immutable, this is not always enforced at the registry level. So instead of using a semver tag, users should be able to reference a module by its OCI digest. CI automation like Dependabot and Renovate could update the digest in the bundle files.

To allow pinning a module by its OCI digest, the Bundle API could contain an optional field `instance.module.digest`.

When both the module version and the digest are specified, Timoni should error out if the digest of the version doesn't match the specified digest.  (suggested by @hiddeco)

When the version and digest are not specified, Timoni should pull the latest version.

When only digest is specified, Timoni should pull the module by digest and extract the semver version from the artifact metadata. Besides the digest, the Timoni's output and in-cluster instance should contain the semver version, so users don't have to look for the actual version in the registry.

**Comment by squaremo** [comment]
> Timoni should pull the latest version.

Is it correct to say that using a version "latest" will get the image most recently pushed with that tag or no tag, rather than the latest version? If so, I think it'll be worth saying explicitly in docs and help text that it's the image with the tag `latest`, since "latest version" suggests it's the highest version pushed, or the version most recently pushed, or at least is ambiguous.

**Comment by stefanprodan** [comment]
@squaremo I tried to capture the `latest` behaviour here https://timoni.sh/module-semver/. But for sure, this needs to be called out in the Bundle docs as well.

**Comment by stefanprodan** [comment]
@squaremo I’ve called out the latest tag explicitly in https://github.com/stefanprodan/timoni/pull/69 let me know if you think this needs more explanations. Thanks
