### ISSUE TITLE
Update CUE Go packages to v0.5.0

### ISSUE THREAD

**Issue by stefanprodan** [stefanprodan/timoni#77]
https://github.com/cue-lang/cue/releases/tag/v0.5.0

**Comment by errordeveloper** [comment]
Is there any concrete feature we want? I've stumbled upon one issue (https://github.com/cue-lang/cue/issues/2325) that was introduced in 0.5.0 and will not get fixed until the next minor release. It was a blocker for some of my code, which doesn't mean it has to be a blocker for Timoni. Perhaps @myitcv could chime in.

**Comment by uhthomas** [comment]
Yes, please. There are major bugs which make timoni impossible to use without 0.5.0.

Not sure exactly what causes it, but it seems there is some trouble with disjunctions such they are just completely ignored and then omitted from the output of `timoni build`. Building timoni from source with cue 0.5.0 resolves the issue.

**Comment by errordeveloper** [comment]
Thomas, could you please reference what bugs you hit?

0.6.0-alpha.1 is out, how about we look forward to beta? It it was up to
me, I would bump to alpha and see what happens.

**Comment by stefanprodan** [comment]
If the cue team ships a new version made for wide consumption, I think we can't delay much the upgrade in Timoni.

We'll need to think of some strategy for dependencies updates, even if we use a bot like @uhthomas suggested in https://github.com/stefanprodan/timoni/issues/110 we still need to deal with breaking changes that will affect Timoni.

**Comment by errordeveloper** [comment]
Unity might help, we should try it: https://github.com/marketplace/cue-unity
