### ISSUE TITLE
references to files in /tmp in error messages are uhelpful

### ISSUE THREAD

**Issue by errordeveloper** [stefanprodan/timoni#82]
Due to that modules are copied to a temporary directory, errors like this can occur:

```
✗ open /var/folders/gm/dnc405js6nlb275l4v2gh_b40000gn/T/timoni1961184784/module/cue.mod/module.cue: no such file or directory
```

This is a little disorienting to the users because files get deleted right away. If copying cannot be avoided, perhaps some other UX measures can be taken, e.g. check `cue.mod/module.cue` up front.

**Comment by stefanprodan** [comment]
This has been fixed
