### ISSUE TITLE
could name and namespace tags be optional?

### ISSUE THREAD

**Issue by errordeveloper** [stefanprodan/timoni#85]
I am not entirely sure why name and namespace are first-class parameters, it would seem more natural to just pass these as values. There are cases where the name needs to be constant, and there are cases where more than one namespace can be used.

**Comment by stefanprodan** [comment]
These are used to create the instances on the cluster, the name is used to uniquely identify the storage (Kubernetes secret) in a namespace. Also the namespace/name identifier is used in bundles and in all the commands involving instances.

**Comment by errordeveloper** [comment]
I didn't realise there was a secret, I should have a look into what it does.

I guess it's just that to some users (like me) it's important that `name` and `namespace` parameters don't become overly prescriptive, so they can still choose to use namespaces whichever way they need to, and don't feel obliged to use `name`. 

Another thought for discussion: perhaps what might make sense is to enable setting `namespace` and `name` from the underlying CUE module.

**Comment by Nalum** [comment]
I'm writing up a module for cert-manger which has multiple deployments, in trying to override `metadata.name` I'm getting the following error:

```sh
❯ make vet
10:48AM INF vetting with default values
10:48AM ERR validation failed:
timoni.instance.objects.deployment.metadata.name: conflicting values "default-controller" and "default":
    ./templates/config.cue:531:15
    ./templates/deployment.cue:11:14
    ./templates/deployment.cue:12:18
    ./timoni.cue:27:12

make: *** [Makefile:35: vet] Error 1
```

So I'll need to create secondary `metadata` that allows changing of name. I don't think it's a massive issue but just wanted to call it out here.

**Comment by Nalum** [comment]
This is the approach I'm going with at the moment

https://github.com/Nalum/cert-manager-module/blob/main/modules/cert-manager/templates/deployment.cue#L11-L20

**Comment by stefanprodan** [comment]
I don't understand why would you need any of this? You can inject the tags with CUE to debug modules, see the debug_values.cue on how to run the command.

**Comment by stefanprodan** [comment]
Ah Ok, I get it now, you want a suffix, an example is here: https://github.com/stefanprodan/timoni/blob/da003ac3714b941f37933b76604adcc155781902/examples/minimal/templates/configmap.cue#L15-L22

You're solution to define a `component` seem great to me, one suggestion i would make it to use the standard label from the Timoni APIs

```cue
	_metadata: {
		name:      "\(_config.metadata.name)-\(_component)"
		namespace: _config.metadata.namespace
		labels:    _config.metadata.labels
		labels: "\(timoniv1.#StdLabelComponent)": _component

		if _config.metadata.annotations != _|_ {
			annotations: _config.metadata.annotations
		}
	}
```

**Comment by stefanprodan** [comment]
Going to close this issue as not planned, due to how Timoni's instances work there is no way to make name/namespace optional, an instance is a namespaced object, with it's definition stored in a secret.
