### ISSUE TITLE
Allow for values to be supplied in other formats than cue

### ISSUE THREAD

**Issue by stefanprodan** [stefanprodan/timoni#9]
Currently Timoni expects that end-users who consume modules, to provider their custom values as `.cue` files. To easy adoption we should consider offering YAML and JSON as alternative formats. We could programmatically perform a cue import on the input YAML and JSON files in the CLI, so that Timoni's engine would not have to deal with different formats.

**Comment by verdverm** [comment]
Are you using the `cue/load` package for turning the input files into a Value?

Check out this function: https://github.com/hofstadter-io/hof/blob/_dev/lib/cuetils/runtime.go#L126

It uses the loader and has support for data files.

**Comment by stefanprodan** [comment]
I'm currently using `CompileBytes`, but I'm now considering switching to `cue/load`. Thanks @verdverm
