### ISSUE TITLE
Design a logo for Timoni

### ISSUE THREAD

**Issue by stefanprodan** [stefanprodan/timoni#96]
We're looking for a designer to craft a logo for Timoni and/or a mascot. For the mascot maybe a gopher with a CUE tattoo or chain. For the logo it could be a simple T or some combination of the Kubernetes ship wheel. Any other suggestions are welcome.

**Comment by Nalum** [comment]
Messing around :sweat_smile:

![timoni-t1](https://github.com/stefanprodan/timoni/assets/384180/f4e76530-db33-4edd-b46e-f14cd0aca00c)
![timoni-t2](https://github.com/stefanprodan/timoni/assets/384180/c7cbfa13-f81e-4dab-b6ef-2fa07ff21986)

**Comment by stefanprodan** [comment]
Haha this would breach Kubernetes CC, we can't use their logo, we could use the ship wheel but redesigned like Helm does.

Thanks @Nalum for the effort.

**Comment by Nalum** [comment]
:+1: might mess around some more and maybe read up on it :grin:

**Comment by Nalum** [comment]
Another quick mess
![timoni-t3](https://github.com/stefanprodan/timoni/assets/384180/16a090a8-413e-44df-9fc4-7d5dd240040a)
